// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAppState: () => typedError<EditorWorkspaceState, string>(__TAURI_INVOKE("get_app_state")),
	workspaceAddFiles: (assets: EditorAsset[]) => typedError<null, string>(__TAURI_INVOKE("workspace_add_files", { assets })),
	workspaceRemoveFile: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("workspace_remove_file", { fileId })),
	workspaceSetActiveFile: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("workspace_set_active_file", { fileId })),
	workspaceMoveClip: (fileId: string, clipId: string, startMs: number | null) => typedError<null, string>(__TAURI_INVOKE("workspace_move_clip", { fileId, clipId, startMs })),
	workspaceTrimClipStart: (fileId: string, clipId: string, inPointMs: number | null, startMs: number | null) => typedError<null, string>(__TAURI_INVOKE("workspace_trim_clip_start", { fileId, clipId, inPointMs, startMs })),
	workspaceTrimClipEnd: (fileId: string, clipId: string, outPointMs: number | null) => typedError<null, string>(__TAURI_INVOKE("workspace_trim_clip_end", { fileId, clipId, outPointMs })),
	workspaceSplitClip: (fileId: string, clipId: string, atMs: number | null) => typedError<null, string>(__TAURI_INVOKE("workspace_split_clip", { fileId, clipId, atMs })),
	workspaceDeleteClips: (fileId: string, clipIds: string[]) => typedError<null, string>(__TAURI_INVOKE("workspace_delete_clips", { fileId, clipIds })),
	workspaceSetClipsMuted: (fileId: string, clipIds: string[], muted: boolean) => typedError<null, string>(__TAURI_INVOKE("workspace_set_clips_muted", { fileId, clipIds, muted })),
	workspaceSetRenderProfile: (fileId: string, renderProfile: RenderProfilePayload) => typedError<null, string>(__TAURI_INVOKE("workspace_set_render_profile", { fileId, renderProfile })),
	getLprRuntimeStatus: () => typedError<LprRuntimeStatusPayload, string>(__TAURI_INVOKE("get_lpr_runtime_status")),
	cancelLprRuntimeJob: () => typedError<boolean, string>(__TAURI_INVOKE("cancel_lpr_runtime_job")),
	scanLprTargets: (request: LprTargetScanRequestPayload) => typedError<LprTargetScanResponsePayload, string>(__TAURI_INVOKE("scan_lpr_targets", { request })),
	analyzeLprFrame: (request: LprFrameAnalysisRequestPayload) => typedError<LprFrameAnalysisResponsePayload, string>(__TAURI_INVOKE("analyze_lpr_frame", { request })),
	analyzeLprInterval: (request: LprIntervalAnalysisRequestPayload) => typedError<LprIntervalAnalysisResponsePayload, string>(__TAURI_INVOKE("analyze_lpr_interval", { request })),
	analyzeAiEvidence: (request: AiEvidenceRequestPayload) => typedError<AiEvidenceResponsePayload, string>(__TAURI_INVOKE("analyze_ai_evidence", { request })),
	probeMediaSource: (path: string) => typedError<MediaProbePayload, string>(__TAURI_INVOKE("probe_media_source", { path })),
	saveGeneratedMediaAsset: (sourcePath: string, outputPath: string) => typedError<null, string>(__TAURI_INVOKE("save_generated_media_asset", { sourcePath, outputPath })),
	exportFrameImage: (request: FrameExportRequest) => typedError<null, string>(__TAURI_INVOKE("export_frame_image", { request })),
	exportLprEvidence: (request: LprEvidenceExportRequestPayload) => typedError<LprEvidenceExportResponsePayload, string>(__TAURI_INVOKE("export_lpr_evidence", { request })),
	processTimelineExport: (request: TimelineExportRequest) => typedError<null, string>(__TAURI_INVOKE("process_timeline_export", { request })),
};

/* Types */
export type AiEvidenceKeyframePayload = {
	frame: AiEvidenceTimelineFrameRefPayload,
	description: string,
	overlay: AiEvidenceOverlayBoxPayload | null,
	selectedForTargetResolution: boolean | null,
	keyframeSource: string | null,
	descriptionSource: string | null,
	boxSource: string | null,
	isValidForUserFacingOutput: boolean | null,
};

export type AiEvidenceOverlayBoxPayload = {
	normalizedBox: VideoMarkerRectPayload | null,
	pixelBox: AiEvidencePixelBoxPayload | null,
	frameWidth: number,
	frameHeight: number,
};

export type AiEvidencePixelBoxPayload = {
	x: number,
	y: number,
	width: number,
	height: number,
};

export type AiEvidenceProviderKind = "mock" | "gemini" | "local";

export type AiEvidenceRequestPayload = {
	sourcePath: string,
	description: string,
	markerRect: VideoMarkerRectPayload | null,
	compressionMode: OutputCompressionModePayload,
	audioBitrateKbps: number | null,
	targetVehicleKind: LprVehicleKind,
	countryHints: string[],
	analysisProfileId: string | null,
	enableDeveloperDiagnostics: boolean | null,
	coarseSampleEveryMs: number | null,
	fineSampleEveryMs: number | null,
	fineWindowPaddingMs: number | null,
	maxKeyframes: number | null,
	requestId: string | null,
};

export type AiEvidenceResponsePayload = {
	requestId: string | null,
	description: string,
	summary: string,
	provider: AiEvidenceProviderKind,
	interval: TimelineIntervalSelectionPayload | null,
	plateNumber: string | null,
	plateCandidate: LprPlateCandidatePayload | null,
	primaryAnchor: AiEvidenceTimelineFrameRefPayload | null,
	targetSelection: AiEvidenceTargetSelectionPayload | null,
	keyframes: AiEvidenceKeyframePayload[],
	keyframeCountReason: string | null,
	toolCalls: AiEvidenceToolCallPayload[],
	projection: AiEvidenceSharedProjectionPayload,
	clipPath: string | null,
	runtime: LprRuntimeStatusPayload,
};

export type AiEvidenceSharedProjectionPayload = {
	interval: TimelineIntervalSelectionPayload | null,
	targetTracks: LprTargetTrackPayload[],
	analysisTrack: LprTargetTrackPayload | null,
	selectedTargetTrackId: string | null,
	samples: LprFrameSamplePayload[],
	candidates: LprPlateCandidatePayload[],
	acceptedCandidateId: string | null,
	review: LprReviewStatePayload | null,
	provenance: LprAnalysisProvenancePayload | null,
	decision: LprDecisionTrace | null,
};

export type AiEvidenceTargetSelectionPayload = {
	anchorFrameId: string,
	selectedTrackId: string | null,
	selectedCandidateId: string | null,
	confidence: number | null,
	rationale: string,
	selectedBox: AiEvidenceOverlayBoxPayload | null,
};

export type AiEvidenceTimelineFrameRefPayload = {
	frameId: string,
	timeMs: number | null,
	sequenceIndex: number,
	label: string,
	imagePath: string | null,
	frameWidth: number,
	frameHeight: number,
};

export type AiEvidenceToolCallPayload = {
	stage: string,
	toolName: string,
	inputSummary: string,
	outputSummary: string,
	startedAtMs: number | null,
	completedAtMs: number | null,
	success: boolean,
};

export type EditorAnalysisState = {
	lprRuntimeStatus: LprRuntimeStatusPayload | null,
	lprSessionsByFileId: { [key in string]: any },
	aiEvidenceSessionsByFileId: { [key in string]: any },
};

export type EditorAsset = {
	id: string,
	name: string,
	path: string,
	fileSize?: number | null,
	createdAt?: string,
	modifiedAt?: string,
	status?: string,
	url: string | null,
	thumbnailUrl: string | null,
	hasVideo: boolean,
	hasAudio: boolean,
	durationMs: number | null,
	fps: number | null,
	audioBitrateKbps: number | null,
	width: number | null,
	height: number | null,
	kind: string | null,
};

export type EditorFileState = {
	id: string,
	asset: EditorAsset,
	track: TimelineTrackPayload,
	clips: TimelineClipPayload[],
	renderProfile: RenderProfilePayload,
};

export type EditorWorkspaceState = {
	workspaceName: string,
	activeFileId: string | null,
	files: EditorFileState[],
	analysis: EditorAnalysisState,
};

export type ExportSnapshotPayload = {
	fileId: string,
	fileName: string,
	workspaceName: string,
	suggestedName: string,
	timelineDurationMs: number | null,
	hasVideo: boolean,
	hasAudio: boolean,
	dominantWidth: number | null,
	dominantHeight: number | null,
	sources: ExportSource[],
	tracks: TimelineTrackPayload[],
	clips: TimelineClipPayload[],
	renderProfile: RenderProfilePayload,
};

export type ExportSource = {
	id: string,
	name: string,
	path: string,
	hasVideo: boolean,
	hasAudio: boolean,
	width: number | null,
	height: number | null,
};

export type FrameExportRequest = {
	outputPath: string,
	sourcePath: string,
	timeMs: number | null,
	markerRect: VideoMarkerRectPayload | null,
	compressionMode: OutputCompressionModePayload,
};

export type LprAnalysisIntent = "interactive-short-range" | "interactive-range" | "interactive-dense-range" | "ai-evidence-range";

export type LprAnalysisOptionsPayload = {
	persistArtifacts: boolean | null,
	artifactDir: string | null,
	trackerMode: string | null,
	fusionMode: string | null,
	restorationMode: string | null,
	recognizerBackend: string | null,
	temporalEvidenceMode: string | null,
	sequenceReviewMode: string | null,
	enableRectification: boolean | null,
	enableEnhancement: boolean | null,
	enableRecognizerComparison: boolean | null,
	debugTag: string | null,
	ocrModelNames: string[] | null,
	maxPlateCandidates: number | null,
	trackerHighConfidence: number | null,
	trackerLowConfidence: number | null,
	maxTrackingGap: number | null,
	minAlignmentScore: number | null,
	enableReliabilityGates: boolean | null,
	minAcceptedConfidence: number | null,
	minCandidateMargin: number | null,
	minIntervalSupportFrames: number | null,
	minSequencePersistence: number | null,
	maxSequenceGapCount: number | null,
	temporalWindowMs: number | null,
	temporalNeighborCount: number | null,
	maxEvidenceSampleCount: number | null,
	anchorBurstCount: number | null,
};

export type LprAnalysisProvenancePayload = {
	requestId: string | null,
	command: string,
	analysisProfileId: string | null,
	developerDiagnosticsEnabled: boolean,
	runtimeVersion: string | null,
	restorationMode: string | null,
	recognizerBackend: string | null,
	temporalEvidenceMode: string | null,
	sequenceReviewMode: string | null,
	emittedAtMs: number | null,
};

export type LprAnchorStatus = "valid" | "missing-selection" | "outside-interval" | "not-detected" | "mismatched" | "degraded";

export type LprArtifactStage = "raw" | "original" | "rectified" | "enhanced" | "restored" | "temporal-restored" | "fused";

export type LprDecisionSource = "single-frame" | "temporal-fusion" | "cross-frame-vote" | "user-selected" | "fused-image" | "fused-char" | "temporal-restored" | "support-carry" | "legacy-vote";

export type LprDecisionTrace = {
	source: LprDecisionSource,
	candidateId: string | null,
	sampleId: string | null,
	frameTimeMs: number | null,
	stage: LprArtifactStage | null,
	supportFrameCount: number,
	agreementRatio: number | null,
	margin: number | null,
};

export type LprEvidenceExportRequestPayload = {
	outputPath: string,
	sourcePath: string,
	timeMs: number | null,
	markerRect: VideoMarkerRectPayload | null,
	compressionMode: OutputCompressionModePayload,
	interval: TimelineIntervalSelectionPayload | null,
	targetTrack: LprTargetTrackPayload | null,
	acceptedCandidate: LprPlateCandidatePayload | null,
	candidates: LprPlateCandidatePayload[],
	samples: LprFrameSamplePayload[],
	review: LprReviewStatePayload | null,
	provenance: LprAnalysisProvenancePayload | null,
};

export type LprEvidenceExportResponsePayload = {
	jsonPath: string,
	imagePath: string,
	bundleDir: string,
	exportedFileCount: number,
	decisionFrameCount: number,
};

export type LprEvidenceReason = "anchor" | "anchor-frame" | "interval-start" | "interval-end" | "scheduled-sample" | "temporal-burst" | "motion-hotspot" | "high-confidence" | "highest-confidence" | "highest-resolution" | "representative" | "temporal-support" | "sharpness-peak";

export type LprFrameAnalysisRequestPayload = {
	sourcePath: string,
	timeMs: number | null,
	markerRect: VideoMarkerRectPayload | null,
	targetVehicleKind: LprVehicleKind,
	selectedTargetBox: VideoMarkerRectPayload | null,
	countryHints: string[],
	analysisProfileId: string | null,
	enableDeveloperDiagnostics: boolean | null,
	analysisOptions: LprAnalysisOptionsPayload | null,
	requestId: string | null,
};

export type LprFrameAnalysisResponsePayload = {
	detections: LprTrackedRegionPayload[],
	sample: LprFrameSamplePayload | null,
	candidates: LprPlateCandidatePayload[],
	acceptedCandidateId: string | null,
	review: LprReviewStatePayload,
	provenance: LprAnalysisProvenancePayload,
	decision: LprDecisionTrace | null,
	runtime: LprRuntimeStatusPayload,
	jobStatus: LprJobStatus | null,
	diagnostics: any | null,
};

export type LprFrameSamplePayload = {
	id: string,
	timeMs: number | null,
	targetBox: VideoMarkerRectPayload | null,
	plateBox: VideoMarkerRectPayload | null,
	quality: LprQualityMetricsPayload | null,
	candidates: LprPlateCandidatePayload[],
	imagePath: string | null,
	selection: LprSampleSelection | null,
	ocrInput: LprOcrInput | null,
	temporalSupport: LprTemporalSupport | null,
	diagnostics: any | null,
};

export type LprIntervalAnalysisRequestPayload = {
	sourcePath: string,
	interval: TimelineIntervalSelectionPayload,
	anchorTimeMs: number | null,
	targetVehicleKind: LprVehicleKind,
	selectedTargetBox: VideoMarkerRectPayload | null,
	selectedTargetTrackId: string | null,
	countryHints: string[],
	sampleEveryMs: number | null,
	maxSamples: number | null,
	analysisIntent: LprAnalysisIntent | null,
	latencyBudgetMs: number | null,
	analysisProfileId: string | null,
	enableDeveloperDiagnostics: boolean | null,
	analysisOptions: LprAnalysisOptionsPayload | null,
	requestId: string | null,
};

export type LprIntervalAnalysisResponsePayload = {
	targetTracks: LprTargetTrackPayload[],
	analysisTrack: LprTargetTrackPayload | null,
	samples: LprFrameSamplePayload[],
	candidates: LprPlateCandidatePayload[],
	acceptedCandidateId: string | null,
	review: LprReviewStatePayload,
	provenance: LprAnalysisProvenancePayload,
	decision: LprDecisionTrace | null,
	summary: string,
	runtime: LprRuntimeStatusPayload,
	jobStatus: LprJobStatus | null,
	tracking: LprTrackingSummary | null,
	sequence: LprSequenceSummary | null,
	diagnostics: any | null,
};

export type LprJobStatus = "idle" | "queued" | "running" | "completed" | "failed" | "cancelled" | "degraded";

export type LprLegibilityLevel = "perfect" | "good" | "poor" | "illegible" | "unknown";

export type LprOcrInput = {
	stage: LprArtifactStage,
	variant: string,
	source: LprDecisionSource,
	imagePath: string | null,
	supportFrameCount: number,
};

export type LprPlateCandidatePayload = {
	id: string,
	text: string,
	confidence: number | null,
	source: string,
	frameTimeMs: number | null,
	countryCode: string | null,
	box: VideoMarkerRectPayload | null,
	quality: LprQualityMetricsPayload | null,
	diagnostics: any | null,
};

export type LprQualityMetricsPayload = {
	sharpness: number | null,
	contrast: number | null,
	plateArea: number | null,
	angleScore: number | null,
	occlusionScore: number | null,
	glareScore: number | null,
	legibilityScore: number | null,
	overallScore: number | null,
	legibilityLevel: LprLegibilityLevel,
};

export type LprReviewStatePayload = {
	status: LprReviewStatus,
	acceptedCandidateId: string | null,
	suggestedCandidateId: string | null,
	reasons: string[],
};

export type LprReviewStatus = "accepted" | "review-required" | "no-candidate";

export type LprRuntimeStatusPayload = {
	available: boolean,
	pythonExecutable: string | null,
	runtimeScript: string | null,
	version: string | null,
	missingPackages: string[],
	installedPackages: string[],
	detail: string,
};

export type LprSampleSelection = {
	selected: boolean,
	priority: number | null,
	reasons: LprEvidenceReason[],
};

export type LprSequenceSummary = {
	sequenceTier: LprSequenceTier,
	dominantText: string | null,
	persistenceRatio: number | null,
	supportFrameCount: number,
	sampleCount: number,
	supportFrameGapCount: number,
	predictionSwitchCount: number,
	characterConsistency: (number | null)[],
	characterConsistencyMean: number | null,
};

export type LprSequenceTier = "stable" | "drifting" | "gapped" | "fragmented";

export type LprTargetScanRequestPayload = {
	sourcePath: string,
	timeMs: number | null,
	markerRect: VideoMarkerRectPayload | null,
	targetVehicleKind: LprVehicleKind,
	requestId: string | null,
};

export type LprTargetScanResponsePayload = {
	detections: LprTrackedRegionPayload[],
	runtime: LprRuntimeStatusPayload,
};

export type LprTargetTrackPayload = {
	id: string,
	className: string,
	label: string,
	confidence: number | null,
	frames: LprTrackedRegionPayload[],
	diagnostics: any | null,
};

export type LprTemporalSupport = {
	strategy: string,
	referenceTimeMs: number | null,
	supportFrameCount: number,
	supportWindowMs: number | null,
	supportTimes: (number | null)[],
	meanAlignmentScore: number | null,
	meanQualityScore: number | null,
	sourceStage: LprArtifactStage,
	selectedStage: LprArtifactStage,
};

export type LprTrackedRegionPayload = {
	id: string,
	timeMs: number | null,
	box: VideoMarkerRectPayload,
	confidence: number | null,
	className: string,
	diagnostics: any | null,
};

export type LprTrackingSummary = {
	trackingTier: LprTrackingTier,
	anchorStatus: LprAnchorStatus,
	coverageRatio: number | null,
	trackedFrameCount: number,
	requestedFrameCount: number,
	degradedReason: string | null,
	terminatedEarly: boolean,
};

export type LprTrackingTier = "full" | "partial" | "detection-fallback" | "anchor-only" | "anchor-invalid";

export type LprVehicleKind = "any" | "vehicle" | "motorcycle" | "car" | "truck" | "bus";

export type MediaProbePayload = {
	durationMs: number | null,
	hasVideo: boolean,
	hasAudio: boolean,
	fps: number | null,
	audioBitrateKbps: number | null,
	width: number | null,
	height: number | null,
};

export type OutputCompressionModePayload = "standard" | "compact";

export type RenderProfilePayload = {
	format: string,
	fps: number,
	videoQuality: string | null,
	audioBitrateKbps: number | null,
	compressionMode: OutputCompressionModePayload,
};

export type TimelineClipPayload = {
	id: string,
	assetId: string,
	trackId: string,
	startMs: number | null,
	inPointMs: number | null,
	outPointMs: number | null,
	muted: boolean,
};

export type TimelineExportRequest = {
	outputPath: string,
	profile: RenderProfilePayload,
	snapshot: ExportSnapshotPayload,
};

export type TimelineIntervalSelectionPayload = {
	startMs: number | null,
	endMs: number | null,
};

export type TimelineTrackPayload = {
	id: string,
	name: string,
	order: number,
};

export type VideoMarkerRectPayload = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

